### ISSUE TITLE
Static representation

### ISSUE THREAD

**Issue by franklingg** [matheusgr/modeligado#21]
Is there a keyword for writing static methods/attributes? Something similar to this, maybe:

![image](https://user-images.githubusercontent.com/61962950/96378134-760c9200-1160-11eb-96b6-8c111bee7f78.png)

**Comment by matheusgr** [comment]
We need to upgrade the modeligado grammar for that.

I propose that each method/attribute can receive modifiers, and the first one should be `static`.

Example:
```
- static count : int
- color : int
```

gojs already has support for underline static method/attributes ( https://github.com/matheusgr/modeligado/blob/1f6cd690086433593a50be5a3a11d9d1ffc84da7/gojs.js#L66 ). We just need to add the `scope` property with value 'c' on the static attribute/method.

**Comment by matheusgr** [comment]
https://github.com/matheusgr/modeligado/pull/22
