### ISSUE TITLE
Allow multi-type generics (i.e. <T, R, ...>) on method parameters

### ISSUE THREAD

**Issue by matheusgr** [matheusgr/modeligado#26]
Example:

```
Aluno
---
---
+ setDetails(details: Map<String, String>): str
---
```

Should not return  `Line 4: Unknow param format details: Map<String, String>`

Modeligado seems to separate parameters by comma, thus a multi-type generics will raise an error.

**Comment by thisames** [comment]
hey i will work on this issue. PR soon 👍

**Comment by matheusgr** [comment]
https://github.com/matheusgr/modeligado/pull/28

done :)
